# Generated by Django 6.1.1 on 2026-09-24 09:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('diet_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('egg', 'Eggetarian'), ('nonveg', 'Non-vegetarian'), ('vegan', 'Vegan')], default='nonveg', max_length=10)),
                ('started_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('walked_km', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Walk (km)')),
                ('brisk_included', models.BooleanField(default=False, verbose_name='Included a brisk stretch')),
                ('mobility_done', models.BooleanField(default=False, verbose_name='Mobility warm-up done')),
                ('strength_done', models.BooleanField(default=False, verbose_name='Strength session done')),
                ('chair_squats_reps', models.PositiveSmallIntegerField(default=0)),
                ('wall_pushups_reps', models.PositiveSmallIntegerField(default=0)),
                ('glute_bridges_reps', models.PositiveSmallIntegerField(default=0)),
                ('bird_dog_reps', models.PositiveSmallIntegerField(default=0)),
                ('plank_seconds', models.PositiveSmallIntegerField(default=0)),
                ('sleep_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('water_liters', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('protein_every_meal', models.BooleanField(default=False, verbose_name='Protein at every meal')),
                ('did_anyway', models.BooleanField(default=False, verbose_name='Did it despite low motivation')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='one_entry_per_user_per_day')],
            },
        ),
    ]
